# ServiceAccount for the Kubernetes Remediation MCP Server
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-remediation-mcp-sa
  labels:
    app: kubernetes-remediation-mcp

---
# ClusterRole with remediation permissions
# Supports: get, describe, logs, edit, patch, delete, scale, rollout,
#           cordon, uncordon, drain, taint, label, annotate
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-remediation-mcp-role
  labels:
    app: kubernetes-remediation-mcp
rules:
  # Core resources - read and write access (secrets excluded)
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
      - configmaps
      - persistentvolumeclaims
      - replicationcontrollers
    verbs: ["get", "list", "watch", "patch", "update", "delete"]

  # Pod logs (read-only)
  - apiGroups: [""]
    resources:
      - pods/log
    verbs: ["get", "list", "watch"]

  # Pod eviction (required for drain)
  - apiGroups: [""]
    resources:
      - pods/eviction
    verbs: ["create"]

  # Events and namespaces (read-only)
  - apiGroups: [""]
    resources:
      - events
      - namespaces
    verbs: ["get", "list", "watch"]

  # Nodes - for cordon, uncordon, drain, taint
  - apiGroups: [""]
    resources:
      - nodes
    verbs: ["get", "list", "watch", "patch", "update", "delete"]

  # Deployments, DaemonSets, ReplicaSets, StatefulSets
  # Supports: scale, rollout restart, edit, patch, delete
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs: ["get", "list", "watch", "patch", "update", "delete"]

  # Scale subresource (for kubectl scale)
  - apiGroups: ["apps"]
    resources:
      - deployments/scale
      - replicasets/scale
      - statefulsets/scale
    verbs: ["get", "patch", "update"]

  # Jobs and CronJobs
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch", "patch", "update", "delete", "create"]

  # Ingresses and NetworkPolicies
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
    verbs: ["get", "list", "watch", "patch", "update", "delete"]

  # HorizontalPodAutoscalers
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch", "patch", "update", "delete"]

---
# ClusterRoleBinding - grants cluster-wide access
# For namespace-scoped access, use RoleBinding instead
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-remediation-mcp-binding
  labels:
    app: kubernetes-remediation-mcp
subjects:
  - kind: ServiceAccount
    name: kubernetes-remediation-mcp-sa
    namespace: default  # Change to your namespace
roleRef:
  kind: ClusterRole
  name: kubernetes-remediation-mcp-role
  apiGroup: rbac.authorization.k8s.io

---
# Alternative: Read-only ClusterRole
# Use this if you want to restrict to read-only operations
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: kubernetes-remediation-mcp-role-readonly
#   labels:
#     app: kubernetes-remediation-mcp
# rules:
#   - apiGroups: [""]
#     resources:
#       - pods
#       - pods/log
#       - services
#       - endpoints
#       - configmaps
#       - secrets
#       - persistentvolumeclaims
#       - events
#       - namespaces
#       - nodes
#       - replicationcontrollers
#     verbs: ["get", "list", "watch"]
#
#   - apiGroups: ["apps"]
#     resources:
#       - deployments
#       - daemonsets
#       - replicasets
#       - statefulsets
#     verbs: ["get", "list", "watch"]
#
#   - apiGroups: ["batch"]
#     resources:
#       - jobs
#       - cronjobs
#     verbs: ["get", "list", "watch"]
#
#   - apiGroups: ["networking.k8s.io"]
#     resources:
#       - ingresses
#       - networkpolicies
#     verbs: ["get", "list", "watch"]
#
#   - apiGroups: ["autoscaling"]
#     resources:
#       - horizontalpodautoscalers
#     verbs: ["get", "list", "watch"]

---
# Alternative: Namespace-scoped Role and RoleBinding
# Use this instead of ClusterRole/ClusterRoleBinding for restricted access
#
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: kubernetes-remediation-mcp-role
#   namespace: target-namespace
#   labels:
#     app: kubernetes-remediation-mcp
# rules:
#   # Same rules as ClusterRole above, but scoped to this namespace
#   - apiGroups: [""]
#     resources: ["pods", "pods/log", "services", "configmaps"]
#     verbs: ["get", "list", "watch", "patch", "update", "delete"]
#   - apiGroups: ["apps"]
#     resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
#     verbs: ["get", "list", "watch", "patch", "update", "delete"]
#
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: kubernetes-remediation-mcp-binding
#   namespace: target-namespace
#   labels:
#     app: kubernetes-remediation-mcp
# subjects:
#   - kind: ServiceAccount
#     name: kubernetes-remediation-mcp-sa
#     namespace: default
# roleRef:
#   kind: Role
#   name: kubernetes-remediation-mcp-role
#   apiGroup: rbac.authorization.k8s.io
