# Prefect MCP Credentials Secret
# Replace the placeholder values with your actual Prefect credentials
#
# To create the secret:
#   kubectl apply -f secret.yaml -n <namespace>
#
# Option A: Prefect Cloud
#   1. Get your Account ID and Workspace ID from Prefect Cloud settings
#   2. Generate an API key at https://app.prefect.cloud/my/api-keys
#
# Option B: Self-hosted Prefect (no auth)
#   Just set the API URL, leave the key empty or remove it
#
# Option C: Self-hosted Prefect (with basic auth)
#   Uncomment prefect-api-auth-string and set username:password
#
apiVersion: v1
kind: Secret
metadata:
  name: prefect-mcp-credentials
  labels:
    app: prefect-mcp
type: Opaque
stringData:
  # Required: Prefect API URL
  # Prefect Cloud: https://api.prefect.cloud/api/accounts/<ACCOUNT_ID>/workspaces/<WORKSPACE_ID>
  # Self-hosted:   http://prefect-server.prefect.svc.cluster.local:4200/api
  prefect-api-url: "http://prefect-server.prefect.svc.cluster.local:4200/api"

  # For Prefect Cloud: uncomment and set your API key from https://app.prefect.cloud/my/api-keys
  # For self-hosted without auth: leave this commented out
  # prefect-api-key: "pnu_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

  # For self-hosted Prefect with basic auth (uncomment in deployment.yaml too):
  # prefect-api-auth-string: "admin:password123"
