apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-mcp-server
  namespace: mariadb
  labels:
    app: mariadb-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-mcp-server
  template:
    metadata:
      labels:
        app: mariadb-mcp-server
    spec:
      containers:
      - name: mcp-server
        image: me-west1-docker.pkg.dev/robusta-development/development/mariadb-http-mcp-minimal:1.0.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: DB_HOST
          value: "mariadb-service.mariadb.svc.cluster.local"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-mcp-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-mcp-secret
              key: password
        - name: DB_NAME
          value: "testdb"

        # MCP server configuration
        - name: MCP_READ_ONLY
          value: "true"  # This enforces read-only SQL mode
        - name: MCP_MAX_POOL_SIZE
          value: "5"    # Connection pool size

        # No SSL for internal cluster communication
        - name: DB_SSL
          value: "false"

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-mcp-server
  namespace: mariadb
  labels:
    app: mariadb-mcp-server
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: mariadb-mcp-server